### ISSUE TITLE
Expand selection with shift+home & shift+end doesn't work

### ISSUE THREAD

**Issue by AdamAndersonFalafelSoftware** [jedmao/vscode-tabsanity#6]
Normally you can expand selection to start/end of line with these key combinations, but with TabSanity installed, it just causes the cursor to return to the start of the selection. E.g. with the cursor on Ln 1, Col 10, I hold Shift and press down arrow. Now the cursor is on Ln 2, Col 10 with one full wrapped line selected. Continuing to hold Shift, if I press End do expand selection to the end of the line, the cursor instead snaps back to Ln1, Col 10.

**Comment by jednano** [comment]
Unable to reproduce on TabSanity v0.0.8. What version are you on?

**Comment by AdamAndersonFalafelSoftware** [comment]
I am not sure; I thought I was up-to-date, but after uninstalling and reinstalling, the scenario above now works as expected. Sorry for the false alarm!
