### ISSUE TITLE
Can't use shift+home to select to beginning of line

### ISSUE THREAD

**Issue by factormystic** [jedmao/vscode-tabsanity#9]
Refiled here, from https://github.com/Microsoft/vscode/issues/10197

Steps to Reproduce: 
1. Open a file (I have tested this with .rb, .json, and .html files)
2. Click on the middle of a code line with indentation
3. Press <kbd>home</kbd> once & observe that the caret to the beginning of the text, after the indentation whitespace (**correct**)
4. Press <kbd>home</kbd> once more & observe that the caret moves to the beginning of the line, before the indentation whitespace (**correct**)
5. Press <kbd>home</kbd> once more & observe that the caret moves to the beginning of the text, after the indentation whitespace (**correct**)
6. Press <kbd>shift</kbd> + <kbd>home</kbd> & observe that nothing happens (**incorrect**). What should happen is that the caret should be at the beginning of the line with indentation whitespace selected.

**Comment by jednano** [comment]
Thanks for the excellent steps to reproduce. I am able to reproduce on the latest version of TabSanity.

That said, I'm not sure when I can devote any time to fix it, so help is much wanted. I believe the latest vscode release notes gave us a different way to tap into the keyboard navigation with their API, so I wanted to do some research on that front as well.

Accepting PRs.

**Comment by daniellittledev** [comment]
I can take a stab at this issue

**Comment by jednano** [comment]
Thanks @Lavinski for the fix! I've published the fix in version 0.0.9.
